version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/laravel-app
    # overwrite: true
# file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1200
      runas: root
    - location: scripts/start_server.sh
      timeout: 1200
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 1200
      runas: root