version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 22
    commands:
      - php -v
      - echo Installing Composer
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo Installing npm
      - npm install -g npm
  pre_build:
    commands:
      - php -v
      - echo Installing dependencies
      - composer install --prefer-dist --no-interaction
      - npm install
      - touch database/database.sqlite
      - php artisan migrate --force --env=testing
  build:
    commands:
      - npm run build
      - echo Running tests
      - php artisan test --env=testing
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - scripts/**
    - appspec.yml
    - '**/*'


cache:
  paths:
    - vendor/**
    - node_modules/**