version: 0.2
phases:
  install:
    runtime-versions:
      # php: 8.2
      nodejs: 22
    commands:
      - git clone https://github.com/phpenv/phpenv.git ~/.phpenv
      - export PATH="$HOME/.phpenv/bin:$PATH"
      - eval "$(phpenv init -)"
      - git clone https://github.com/php-build/php-build.git ~/.phpenv/plugins/php-build
      - phpenv install 8.2
      - phpenv global 8.2
      - rm -rf /tmp/*
      
      - echo Installing Composer
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo Installing npm
      - npm install -g npm
  pre_build:
    commands:
      - echo Installing dependencies
      - composer install --prefer-dist --no-interaction
      - npm install
      # - cp .env.example .env
      # - php artisan key:generate
      # - php artisan migrate --force
  build:
    commands:
      - echo Running tests
      # - ./vendor/bin/phpunit
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - scripts/**
    - appspec.yml
    - '**/*'

cache:
  paths:
    - vendor/**
    - node_modules/**