version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 22
    commands:
      # - echo Installing Composer
      # - curl -sS https://getcomposer.org/installer | php
      # - mv composer.phar /usr/local/bin/composer
      # - echo Installing npm
      # - npm install -g npm

      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php ;
      - php -r "unlink('composer-setup.php');" ;
      - mv composer.phar /usr/local/bin/composer
  pre_build:
    commands:
      - echo Installing dependencies
      - composer install --prefer-dist --no-interaction
      - npm install
      # - cp .env.example .env
      # - php artisan key:generate
      # - php artisan config:cache
      # - php artisan migrate --force
  build:
    commands:
      - echo Running tests
      # - ./vendor/bin/phpunit
  post_build:
    commands:
      - echo Build completed

env:
  variables:
    AWS_SDK_LOAD_CONFIG: 1
    
artifacts:
  files:
    - scripts/**
    - appspec.yml
    - '**/*'

cache:
  paths:
    - vendor/**
    - node_modules/**